from typing import Any

class UserStats:
    balance: int
    air_purchased: int
    priority_messages: int
    sent_count: int
    received_count: int
    is_vip: bool
    anon_code: str
    code_auto_refresh: str
    show_vip_cats: bool
    show_air: bool
    show_priority: bool
    show_sent: bool
    show_received: bool
    show_achievements: bool

class SenderWithMessage:
    sender_id: int
    user_msg_id: int

class SenderWithCode:
    sender_id: int
    anon_code: str

class BannedUser:
    user_id: int
    anon_code: str

def init_db(db_path: str) -> Any: ...
def is_banned(user_id: int) -> Any: ...
def ban_user(user_id: int, anon_code: str) -> Any: ...
def delete_old_user_code_records(user_id: int, old_code: str) -> Any: ...
def unban_user(user_id: int) -> Any: ...
def regenerate_user_code(user_id: int) -> Any: ...
def register_user(user_id: int, referrer_id: int | None = None) -> Any: ...
def get_user_stats(user_id: int) -> Any: ...
def update_user_setting(user_id: int, key: str, value: str) -> Any: ...
def waste_priority_message(user_id: int) -> Any: ...
def increment_sent_count(user_id: int) -> Any: ...
def increment_received_count(user_id: int) -> Any: ...
def add_message(
    admin_msg_id: int,
    sender_id: int,
    anon_code: str,
    is_priority: bool,
    user_msg_id: int,
) -> Any: ...
def get_admin_msg_id_by_user_msg_id(sender_id: int, user_msg_id: int) -> Any: ...
def get_sender_with_message_by_admin_msg(admin_msg_id: int) -> Any: ...
def take_balance(amount: int, user_id: int) -> Any: ...
def increment_priority_messages(user_id: int) -> Any: ...
def set_vip(user_id: int, vip: bool) -> Any: ...
def increment_air_purchased(user_id: int) -> Any: ...
def get_banned_users() -> Any: ...
def get_banned_user_id_by_anon_code(anon_code: str) -> Any: ...
def get_sender_with_code_by_admin_msg(admin_msg_id: int) -> Any: ...
def create_payment(charge_id: str, user_id: int, payload: str) -> Any: ...
def give_balance(amount: int, user_id: int) -> Any: ...
def get_banned_anon_code_by_user_id(user_id: int) -> Any: ...
def get_payment_user_id_by_charge_id(charge_id: str) -> Any: ...
def set_payment_status_by_charge_id(charge_id: str, status: str) -> Any: ...
def batch_set_payment_status_by_charge_ids(
    charge_ids: list[str], status: str
) -> Any: ...
def get_success_charge_ids_by_user_id(user_id: int) -> Any: ...
def get_all_user_ids() -> Any: ...
def get_user_id_by_id_or_code(identifier: str) -> Any: ...
def grant_achievement(user_id: int, ach_id: str) -> Any: ...
def get_user_achievements(user_id: int) -> Any: ...
def get_user_achievements_count(user_id: int) -> Any: ...
def increment_priority_sent_count(user_id: int) -> Any: ...
def increment_total_spent_stars(user_id: int, amount: int) -> Any: ...
def increment_answer_streak(user_id: int) -> Any: ...
def check_and_grant_achievements(user_id: int) -> Any: ...
